---
abstract: 'Debug perl while its running.'
author:
  - 'Tim Potapov <tim.potapov[AT]gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Runtime-Debugger
provides:
  Runtime::Debugger:
    file: lib/Runtime/Debugger.pm
    version: '0.03'
requires:
  PadWalker: '2.5'
  Term::ReadLine::Gnu: '1.44'
  perl: '5.012'
resources:
  bugtracker: https://github.com/poti1/runtime-debugger/issues
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: https://github.com/poti1/runtime-debugger
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
